language: node_js

node_js:
  - stable

install:
  - npm install

before_script:
  - mysql -u root -p "" < ./builder/CLIPS_structure.sql
  - mysql -u root -p "" < ./builder/CLIPS_data.sql

script:
  - npm test

notifications:
  slack: beaconstrips:1kjxyOQu6KcR1XbAr8aRTfCM
